import type { Metadata } from "next";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Porte Folio Lucie Monteiro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
        />
      </head>
      <link rel="icon" href="/favicon.ico" />
      <body>{children}</body>
    </html>
  );
}
